### ISSUE TITLE
TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by 3isenHeiM** [mgeeky/tomcatWarDeployer#21]
I'm getting this error when launching the script (python 2.7 or python 3.9).

```
Traceback (most recent call last):
  File "/home/XXX/GitHub/tomcatWarDeployer/tomcatWarDeployer.py", line 1224, in <module>
    main()
  File "/home/XXX/GitHub/tomcatWarDeployer/tomcatWarDeployer.py", line 1063, in main
    browser, url = browseToManager(
  File "/home/XXX/GitHub/tomcatWarDeployer/tomcatWarDeployer.py", line 863, in browseToManager
    m = re.search('Apache Tomcat/([^<]+)', data)
  File "/usr/lib/python3.9/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
```

What can I do to solve it ?

**Comment by ClubMontana** [comment]
problem is that your regex is a string but html is bytes, either decode the bytes to a string or use a bytes regex

**Comment by ClubMontana** [comment]
or refer here https://stackoverflow.com/questions/31019854/typeerror-cant-use-a-string-pattern-on-a-bytes-like-object-in-re-findall

**Comment by Itrekr** [comment]
Added a request to fix this in the code: https://github.com/mgeeky/tomcatWarDeployer/pull/22
